name: project_sync_pipeline

on:
  push:
    branches-ignore:
      - 'skip-ci-*'
  pull_request:
    branches-ignore:
      - 'skip-ci-*'

env:
  REPOSITORY_MIRROR: "git@github.com:EpitechPromo2027/B-CPP-500-NAN-5-1-rtype-steven.gandon.git"

jobs:
  mirror_repository:

    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Fetch repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to target repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.REPOSITORY_MIRROR }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
